openapi: 3.0.3
info:
  title: API Citas Médicas
  version: 1.0.0
paths:
  /appointments:
    post:
      summary: Crear nueva cita
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insuredId:
                  type: string
                scheduleId:
                  type: integer
                countryISO:
                  type: string
              required:
                - insuredId
                - scheduleId
                - countryISO
      responses:
        '200':
          description: Cita creada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  appointmentId:
                    type: string
  /appointments/{appointmentId}:
    get:
      summary: Obtener cita por ID
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Información de la cita
          content:
            application/json:
              schema:
                type: object
                properties:
                  appointmentId:
                    type: string
                  insuredId:
                    type: string
                  scheduleId:
                    type: integer
                  countryISO:
                    type: string
                  status:
                    type: string
                  createdAt:
                    type: string
        '404':
          description: Cita no encontrada
